name: Production Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - production
jobs:
  if-merged:
    name: Merge Success
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The Staging PR was merged into Production

    - name: Telegram Notification
      if: ${{ failure() }}
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TELE_BOT_TOKEN }}
        chatId: ${{ secrets.TELE_CHAT_ID }}
        jobStatus: ${{ job.status }}
        skipSuccess: true

  deploy-production:
    name: Deploy Production
    needs: if-merged
    runs-on: self-hosted
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0

      - name: Get Version
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: ./helm/version.env

      - name: Flux Deploy to Production
        run: |
          flux create source helm odoo-prod --namespace=odoo-prod --url=https://cx-harbor.btech.id/chartrepo/cusex --interval=10m
          flux create helmrelease odoo-prod --namespace=odoo-prod --source=HelmRepository/odoo-prod --release-name=odoo --chart=odoo --chart-version="${{ env.VERSION }}" --values=./helm/odoo/values-prod.yaml

      - name: Telegram Notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELE_BOT_TOKEN }}
          chatId: ${{ secrets.TELE_CHAT_ID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
