---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-prod-web
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume/odoo-prod-web"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-prod-addons
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume/odoo-prod-addons"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-prod-web-claim
  namespace: odoo-prod
spec:
  volumeName: odoo-prod-web
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-prod-addons-claim
  namespace: odoo-prod
spec:
  volumeName: odoo-prod-addons
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi