---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo-prod
  labels:
    app: odoo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-prod
  template:
    metadata:
      labels:
        app: odoo-prod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - tambun-worker2
      initContainers:
        - name: set-vol-ownership
          image: busybox
          command: ["/bin/chown", "-R", "101:101", "/var/lib/odoo", "/mnt/extra-addons"]
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-web
            - mountPath: /mnt/extra-addons
              name: odoo-addons
      containers:
        - name: odoo
<<<<<<< HEAD
          image: cx-harbor.btech.id/cusex/odoo:16-v2.3.2
=======
          image: cx-harbor.btech.id/cusex/odoo:16-v2.1.2
>>>>>>> parent of 4fb45a2 (Merge pull request #44 from cusex-btech/staging)
          imagePullPolicy: Always
          ports:
            - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-config
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-web
            - mountPath: /mnt/extra-addons
              name: odoo-addons
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: odoo-web
          persistentVolumeClaim:
            claimName: odoo-prod-web-claim
        - name: odoo-addons
          persistentVolumeClaim:
            claimName: odoo-prod-addons-claim
