---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-test-web
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volumes/odoo-test-web"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tambun-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-test-addons
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volumes/odoo-test-addons"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tambun-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-test-web-claim
  namespace: odoo-test
spec:
  volumeName: odoo-test-web
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-test-addons-claim
  namespace: odoo-test
spec:
  volumeName: odoo-test-addons
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi