---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-stg-web
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume/odoo-stg-web"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-stg-addons
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume/odoo-stg-addons"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-stg-web-claim
  namespace: odoo-stg
spec:
  volumeName: odoo-stg-web
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-stg-addons-claim
  namespace: odoo-stg
spec:
  volumeName: odoo-stg-addons
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi