name: CI/CD Odoo Production

on:
  pull_request:
    types:
      - closed
    branches:
      - production
jobs:
  if-merged:
    name: Merge Success
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The Staging PR was merged into Production

  deploy-production:
    name: Deploy Production
    needs: [if-merged]
    runs-on: self-hosted
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production

      - name: ArgoCD Deploy to Production
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login  -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          argocd login --insecure  ${{ secrets.ARGOCD_SERVER }} --username  ${{ secrets.ARGOCD_USER }} --password  ${{ secrets.ARGOCD_PASS}}
          argocd app create odoo-prod --project default --repo https://github.com/cusex-btech/github-actions-odoo.git --revision production --path ./manifests/production --dest-namespace odoo --dest-server https://kubernetes.default.svc --upsert
          argocd --grpc-web app sync odoo-prod --force
          argocd --grpc-web app wait odoo-prod --timeout 600